updated readme.md and contributers.md
gdsc-aec-india/GDSCAEC-WEBSITE pull request #10
Opened 2023-10-21 09:16 UTC by priyanshu9899

### Related Issue
issue #8 -> updated the images link and added setup instruction in readme.md and contributers.md 

### Proposed Changes 
- updated images link in readme.md
- added setup instruction in contributing.md

### Checklist 
- [x] Documentation of the code 
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine

### Screenshots
<img width="865" alt="Screenshot 2023-10-21 at 2 45 09 PM" src="https://github.com/gdsc-aec-india/GDSCAEC-WEBSITE/assets/132668995/b4412bf0-6fef-4bb5-a739-52646f99506b">
<img width="868" alt="Screenshot 2023-10-21 at 2 45 38 PM" src="https://github.com/gdsc-aec-india/GDSCAEC-WEBSITE/assets/132668995/f0498e1e-4405-498d-91e1-f75d9316d41f">

2023-10-21 11:05 UTC, TheCodeVenturer requested changes
In Contributing.md File Update this changes

Edit this
with 
```sh
npm i
npm start
```

as someone can copy paste the codes directly


In Readme.md

- >Here in line 19, 
  >Update it, as it is no longer just an HTML, CSS, and JS Website.
  >Now It is using React with Vite and Tailwind

- >In line 28,29 Add those scripts you added in Contributing.md
  > after git clone ...., Add this scripts:-
  >```sh 
  > cd GDSCAEC-WEBSITE
  > npm i
  > npm start
  > ```

- > After the git commit msg (line 32) add Sync your local clone in our repositories section on github and  Add this script `git pull origin your_branch_name` to resolve your merge conflict locally

2023-10-21 11:05 UTC, paardarshee commented on CONTRIBUTING.md
Edit this
with 
```sh
npm i
npm start
```

as someone can copy paste the codes directly

2023-10-21 11:05 UTC, paardarshee commented on README.md
- >Here in line 19, 
  >Update it, as it is no longer just an HTML, CSS, and JS Website.
  >Now It is using React with Vite and Tailwind

- >In line 28,29 Add those scripts you added in Contributing.md
  > after git clone ...., Add this scripts:-
  >```sh 
  > cd GDSCAEC-WEBSITE
  > npm i
  > npm start
  > ```

- > After the git commit msg (line 32) add Sync your local clone in our repositories section on github and  Add this script `git pull origin your_branch_name` to resolve your merge conflict locally

2023-10-21 11:45 UTC, priyanshu9899 commented
pls add hacktoberfest accepted label in my pr

2023-10-21 11:46 UTC, priyanshu9899 commented on README.md
sure

2023-10-22 07:18 UTC, TheCodeVenturer approved these changes

2023-10-22 07:22 UTC, TheCodeVenturer approved these changes

2023-10-22 07:26 UTC, merged